services:
  wxbot:
    image: zsly-docker.pkg.coding.net/wxbot/public/wxbot:c3a8511
    container_name: wxbot
    restart: on-failure:3
    volumes:
      - ./robot_stat.json:/app/resource/robot_stat.json
      - ./db/:/app/db/
      - ./login_stat.json:/app/WechatAPI/Client/login_stat.json
      - ./logs/:/app/logs/
      - redis-data:/var/lib/redis

volumes:
  redis-data:
    name: redis-data
