name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 触发构建的分支
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Coding.net Docker Registry
        uses: docker/login-action@v1
        with:
          registry: zsly-docker.pkg.coding.net
          username: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
      
      - name: 获取短 SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zsly-docker.pkg.coding.net/wxbot/public/wxbot:${{ env.GIT_SHA } 